// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
Texture2D<float4> _AverageColor;
Texture2D<float1> _Samples;
float _MaxSamples;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 color = _AverageColor[id.xy] * (_Samples[id.xy].r / _MaxSamples);
    color.a = 1;
    Result[id.xy] = color;
}
